### ISSUE TITLE
Timestamp mechanism for filename generation needs to be more unique

### ISSUE THREAD

**Issue by khoomeister** [groupon/shared-store#4]
When running tests that create many instances of shared store almost simultaneously, I'm getting unhandled rejection errors because the files are clobbering each other.  This is noticeable during [cleanup](https://github.com/groupon/shared-store/blob/master/src/cache.coffee#L65-L71).

Example output:
```
    ✓ reads CSON
    ✓ reads JSON
Unhandled rejection Error: ENOENT, unlink '/some-path/tmp/config/2015-03-12T214330401Z.json'

  Some library
    ✓ does something here
    ✓ doing more awesome here

Unhandled rejection Error: ENOENT, unlink '/some-path/tmp/config/2015-03-12T214330439Z.json'
 ```

I tried adding a simple random number generator to the [timestampName](https://github.com/groupon/shared-store/blob/master/src/cache.coffee#L57-L59) method, which 'nixed the errors.

Unless there's a better solution, making the filename generation more unique should solve the problem.

**Comment by jkrems** [comment]
I think it would be enough to gracefully handle `ENOENT` on deletion. We shouldn't change how the library works based on test-specific conditions. I don't think it's an actual use case that someone boots up and tears down multiple instances of shared-store in the same second and creating enough config files in the meantime that they would be collected.

**Comment by khoomeister** [comment]
OK, that makes sense - thanks!
