### ISSUE TITLE
shared-store temp directory possible issue with path length

### ISSUE THREAD

**Issue by khoomeister** [groupon/shared-store#5]
Our README.md tells users to put their shared-store temp directory here:

```javascript
var store = new SharedStore({
  temp: 'tmp/config',
```

Should we change this considering the [issue node has with long paths](https://gist.github.com/jcfrancisco/443dedfd7a5c79fb5f35)?  If so, what do you think it should be changed to?

**Comment by jkrems** [comment]
I don't think we had any problems with that so far. And I actually can no longer replicate the results in the gist on my machine. I don't think we *can* change this.

**Comment by khoomeister** [comment]
That's weird - oh well, it's not hard to fix, so it's better to cross that bridge if & when we get to it.
